- .github/workflows/build-and-test-differential.yaml
- lanelet2_extension_python/src/projection.cpp
- lanelet2_extension_python/src/utility.cpp
This PR has fixed [the clang-tidy errors](https://github.com/autowarefoundation/autoware_lanelet2_extension/pull/2#issuecomment-2089167474).
> fix: fix clang-tidy errors

- autoware_lanelet2_extension/README.md
- autoware_lanelet2_extension/include/autoware_lanelet2_extension/localization/landmark.hpp
- autoware_lanelet2_extension/include/autoware_lanelet2_extension/utility/message_conversion.hpp
- autoware_lanelet2_extension/lib/landmark.cpp
- autoware_lanelet2_extension/lib/message_conversion.cpp
- autoware_lanelet2_extension/package.xml
- autoware_lanelet2_extension/test/src/test_message_conversion.cpp
- autoware_lanelet2_extension/test/src/test_route_checker.cpp
- build_depends.repos
This PR has made the transition from `autoware_auto_msgs` to `autoware_msgs`.
The commit history is originally from https://github.com/autowarefoundation/autoware_common/compare/main...autoware_msg
> feat: `autoware_msgs` migration

- autoware_lanelet2_extension_python/src/utility.cpp
This PR fixes errors from cpplint in pre-commit ci.
When https://github.com/autowarefoundation/autoware_lanelet2_extension/pull/4 was merged, `// NOLINTNEXTLINE` was used to suppress errors. 
However, cpplint in version 1.6.1 does not recognize `cppcoreguidelines-pro-bounds-pointer-arithmetic` as a supported category and outputs the following error when you run `pre-commit run -a`
```
cpplint..................................................................Failed
- hook id: cpplint
- exit code: 1
autoware_lanelet2_extension_python/src/utility.cpp:70:  Unknown NOLINT error category: cppcoreguidelines-pro-bounds-pointer-arithmetic  [readability/nolint] [5]
autoware_lanelet2_extension_python/src/utility.cpp:86:  Unknown NOLINT error category: cppcoreguidelines-pro-bounds-pointer-arithmetic …
```
> chore(ci): fix cpplint errors from pre-commit ci

- autoware_lanelet2_extension/lib/utilities.cpp
- autoware_lanelet2_extension/src/check_right_of_way.cpp
> build: remove redundant move for build on noble

- autoware_lanelet2_extension/include/autoware_lanelet2_extension/utility/query.hpp
- autoware_lanelet2_extension/lib/query.cpp
Implement a more efficient `getLinkedParkingLot` that do not require providing ALL parking lots.
Instead an efficient query on the lanelet map is used.
Needed for https://github.com/autowarefoundation/autoware.universe/pull/7930
Psim
> perf(query): add faster getLinkedParkingLot function

- autoware_lanelet2_extension/CMakeLists.txt
- autoware_lanelet2_extension/include/autoware_lanelet2_extension/regulatory_elements/Forward.hpp
- autoware_lanelet2_extension/include/autoware_lanelet2_extension/regulatory_elements/bus_stop_area.hpp
- autoware_lanelet2_extension/lib/bus_stop_area.cpp
- autoware_lanelet2_extension/test/src/test_regulatory_elements.cpp
define bus_stop_area in format_v2 namespace
https://github.com/orgs/autowarefoundation/discussions/5097
https://github.com/autowarefoundation/autoware_lanelet2_extension/pull/21
add a new map primitive under format_version2 namespace
none
> feat(lanelet2_extension): add bus_stop_area implementation

- autoware_lanelet2_extension/docs/extra_regulatory_elements.md
- autoware_lanelet2_extension/docs/lanelet2_format_extension.md
depends https://github.com/autowarefoundation/autoware_lanelet2_extension/pull/24
MetaInfo is moved to mandatory section
RightOfWay is moved to the regulatory element section
Crosswalk is moved to the regulatory element section
No Stopping Area is moved to the regulatory element section
No Parking Area is moved to the regulatory element section
Centerline is moved to Optional Tagging section
[contribution guidelines]: …
> docs(autoware_lanelet2_extension): refactor document

- autoware_lanelet2_extension/include/autoware_lanelet2_extension/utility/query.hpp
- autoware_lanelet2_extension/lib/query.cpp
added query function for "bicycle_lane"
with this PR, map_loader can visualize the bicycle_lane (used the map https://github.com/autowarefoundation/autoware.universe/tree/main/planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/test_map/intersection)
> feat(lanelet2_extension): add query for bicycle_lane

- autoware_lanelet2_extension_python/autoware_lanelet2_extension_python/projection/__init__.py
Due to the import order change in https://github.com/autowarefoundation/autoware_lanelet2_extension/pull/14, `example.py` is broken.
```bash
$ python3 autoware_lanelet2_extension_python/example/example.py
Traceback (most recent call last):
File "/ws/autoware_lanelet2_extension_python/example/example.py", line 1, in <module>
from autoware_lanelet2_extension_python.projection import MGRSProjector
File "/ws/install/autoware_lanelet2_extension_python/local/lib/python3.10/dist-packages/autoware_lanelet2_extension_python/projection/__init__.py", line 2, in <module>
import autoware_lanelet2_extension_python._autoware_lanelet2_extension_python_boost_python_projection as _projection_cpp
SystemError: initialization of _autoware_lanelet2_extension_python_boost_python_projection raised unreported …
```
> fix(Python bindings): add missing dependency to lanelet2

- autoware_lanelet2_extension/docs/lanelet2_format_extension.md
This PR will add the autoware prefix to `map_loader` due to the changes in https://github.com/autowarefoundation/autoware.universe/pull/8927 .
This PR should be merged after https://github.com/autowarefoundation/autoware.universe/pull/8927 merged .
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guideli …
> fix: update the github link of map_loader

- autoware_lanelet2_extension/CHANGELOG.rst
- autoware_lanelet2_extension_python/CHANGELOG.rst
This PR fixes the links to the issues in the `CHANGELOG.rst` file
> fix(autoware_lanelet2_extension): fix links to issues in CHANGELOG.rst files

- .github/sync-files.yaml
This PR appends `build-and-test` and `build-and-test-differential` files to `syn-files.yaml`.
Ref.
- https://github.com/autowarefoundation/autoware/pull/5890
- https://github.com/autowarefoundation/autoware_lanelet2_extension/pull/46
- https://github.com/autowarefoundation/autoware_lanelet2_extension/actions/runs/13890551966
None.
None.
> chore(sync-files.yaml): append `build-and-test*.yaml`

- autoware_lanelet2_extension/docs/lanelet2_format_extension.md
This fixes the link to autoware_map_loader package in the README after porting it to Autoware Core.
This must be merged after: https://github.com/autowarefoundation/autoware_core/pull/326
None.
> fix: update link to autoware_map_loader

- autoware_lanelet2_extension/include/autoware_lanelet2_extension/utility/utilities.hpp
- autoware_lanelet2_extension/lib/utilities.cpp
Related Issue: https://github.com/autowarefoundation/autoware.universe/issues/10237
Related PR: https://github.com/autowarefoundation/autoware.universe/pull/10238 
This PR adds `getArcCoordinatesConsideringWaypoints` function to query pose position on a lanelet wrt centerline prioritizing waypoints assigned to the lanelet
None.
None.
> feat: add getArcCoordinatesConsideringWaypoints to enable custom waypoint usage

- autoware_lanelet2_extension/include/autoware_lanelet2_extension/projection/transverse_mercator_projector.hpp
- autoware_lanelet2_extension/lib/transverse_mercator_projector.cpp
add scale_factor for TransverseMercator map.
https://github.com/orgs/autowarefoundation/discussions/5765
see https://github.com/autowarefoundation/autoware_core/pull/340
Please merge this PR after https://github.com/autowarefoundation/autoware_msgs/pull/121.
None.
> feat(projection): add_scale_factor

- autoware_lanelet2_extension/CMakeLists.txt
- autoware_lanelet2_extension/lib/normalize_radian.hpp
- autoware_lanelet2_extension/lib/query.cpp
- autoware_lanelet2_extension/package.xml
- autoware_lanelet2_extension/test/src/test_normalize_radian.cpp
- build_depends.repos
remove dependency on autoware_utils for simplicity.
In a few months, utility/query/ will be removed from this package and lanelet2_extension will become just a pure "extension" of lanelet2.
build passes
None.
None.
> feat(lanelet2_extension)!: remove dependency on autoware_utils

- autoware_lanelet2_extension/lib/query.cpp
This PR fixes the following error.
https://build.ros2.org/job/Rbin_unv8_uNv8__autoware_lanelet2_extension__ubuntu_noble_arm64__binary/99/console
```
03:59:37 /opt/ros/rolling/include/tf2/tf2/utils.h:30:13: error: This header is obsolete, please include 'tf2/utils.hpp' instead [-Werror]
```
None.
None.
> fix(autoware_lanelet2_extension): not use obsolete header

- autoware_lanelet2_extension/lib/visualization.cpp
Function `visualization::polygon2Triangle`  can get polygon with shape of rectangle with redundant points. Function `isWithinTriangle` treats points on the edge of a triangle as _outside point_ and it causes wrong selecting an ear in the polygon: 
This causes creating wrong polygon in the next steps with warning `Could not find valid vertex for ear clipping triangulation. Triangulation result might be invalid`:
The problem was hidden because triangles was very small and invisible in RVIZ.
The enormous amount of logs:
`isWithinTriangle` now checks points on the edge of a triangle.
I just compiled and ran on the carla simulator and logs gone without problems with rendering lanelets.
None.
> fix(autoware_lanelet2_extension): point on the edge of a triangle was  not treated as inside the triangle

- autoware_lanelet2_extension/lib/visualization.cpp
When you run Autoware with AWSIM's nishishinjuku map, it produces 
`Multiple Markers in the same MarkerArray message had the same ns and id: (traffic_light, 70127)`. This happens when the same traffic light is referred by different lanes. (e.g., if you have multiple lanes coming from the same direction)
This will fix the error by checking if the marker was already added.
Tested with nishishinjuku map that you can download from [AWSIM tutorial](https://tier4.github.io/AWSIM/GettingStarted/QuickStartDemo/).
None.
None.
> fix: skip duplicate marker

- autoware_lanelet2_extension/include/autoware_lanelet2_extension/utility/query.hpp
- autoware_lanelet2_extension/lib/query.cpp
Adds getter for general tag for the purpose of visualizing `road_border`.
Note: `road_border` is the recommended boundary tag when creating map [ref](https://docs.pilot.auto/reference-design/common/map-requirements/vector-map-requirements/category_lane/#vm-01-15-%E8%B7%AF%E8%82%A9). Therefore it make sense to support the getter them.
Build success
visualize the border with https://github.com/autowarefoundation/autoware_core/pull/575
None.
None.
> feat: add linestring with type getter

- autoware_lanelet2_extension/CMakeLists.txt
- autoware_lanelet2_extension/include/autoware_lanelet2_extension/regulatory_elements/roundabout.hpp
- autoware_lanelet2_extension/lib/roundabout.cpp
- autoware_lanelet2_extension/test/src/test_regulatory_elements.cpp
This PR adds a roundabout regulatory element.
example:
```
<relation id='1001' visible='true' version='1'>
<member type='relation' ref='1' role='entry' /> 
<member type='relation' ref='2' role='entry' />
<member type='relation' ref='3' role='internal' />
<member type='relation' ref='4' role='exit' />
<member type='relation' ref='5' role='exit' />
<tag k='subtype' v='roundabout' />
<tag k='type' v='regulatory_element' />
</relation>
```
Related universe PR: https://github.com/autowarefoundation/autoware_universe/pull/10944
Related discussion: https://github.com/orgs/autowarefoundation/discussions/6324#discussioncomment-13850712
tested with the map that has roundabout regulatory element
This PR should be merged before 
https://github.com/autowarefoundation/autoware_universe/pull/10944
None.
> feat: add roundabout regulatory element

- autoware_lanelet2_extension/CMakeLists.txt
in order to solve compile error caused by using library boost-geometry
add build option `-Wno-error=maybe-uninitialized` to cmakelist.txt , it is recommended by boost official articles -- https://www.boost.org/doc/libs/1_89_0/libs/optional/doc/html/boost_optional/design/gotchas/false_positive_with__wmaybe_uninitialized.html
parent issue link -- https://github.com/autowarefoundation/autoware_core/issues/623
test with docker file produce by pr in autoware -- https://github.com/autowarefoundation/autoware/pull/6453
build command
colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS='-Wno-error=array-bounds -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=unused-function' --symlink-install --packages-up-to autoware_core
None.
None.
> chore: add build option -Wno-error=maybe-uninitialized
